# Generated by Django 2.2 on 2020-06-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='po',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='po',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='po',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='po',
            name='rejected_reason',
            field=models.BooleanField(default=False),
        ),
    ]
