# Generated by Django 2.2 on 2020-06-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20200628_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('SOUPS', 'SOUPS'), ('SOFT_BEV', 'SOFT_BEV'), ('MOCKTAIL', 'MOCKTAIL'), ('SALAD', 'SALAD'), ('STARTERS', 'STARTERS'), ('STARTERS_NONVEG', 'STARTERS_NONVEG'), ('SHARING', 'SHARING')], default='SOUPS', max_length=100),
        ),
    ]
